language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
jdk:
- oraclejdk8
notifications:
  slack:
    secure: "p74drFbF6h/pCbc+n2DxK/HHri8zO4mzLiDtww7GFRqH/H+tqMZdweyYu6L9wHcjJYbWDJ76FU9Xw0OOVQeZgW/rq1HmE6MDWllrtrit47JDToluhFxbkszawhxDa
oLJ/2XuxZkuf5VVvMT6yhCrz715I6YD1n8tTd/AQ8eocvboGhGXboEac7Q2OXELziUjkmBWtrRehNOUsaVc6puiDi1O1wHWB1M5uDwxJoVCE+1AxxJu9wMwt7YX54YnNGGw3Kfzj
lOgsQhjjGw7t9olukCkCb2sxnM1IiP48y82llnsOT0ihIiPFWsHm9kQkhnxJl6V1T4B54R0w9mA9EuNH2GBLniQkLj1n2Yb2tMHKn2quX34+DKGESYRx/PGU8aGwbOeBgOHcpegO
b0QoHRpmsv28PNSOM47RmhQnvIJL3b1p++lqa2+ow/mM25ZgNcFfTGDN8r1Ssvrt+1hCj7amJZSbbYiTdW0sFtzamOA0Kxrdtghe4A2RqJ29/rEOSH1D/Tlwr6fAjY0xmtZ5FTpg
L8C4qw2KXBN18Dfsiw="